### ISSUE TITLE
Original Firmware Volvo OD 02

### ISSUE THREAD

**Issue by jesusvallejo** [smartgauges/canbox#3]
I have successfully hacked and extracted the original firmware from the Volvo od 02, sw:5. I have extracted it, flashed it into a oem stm32f103 and works as it did with the original mcu. i open this issue so you can add it to this repo in case anyone wants to revert back.
The firmware was extracted using this method: https://github.com/JohannesObermaier/f103-analysis/tree/master/h3\
The extracted firmware here (feel free to add the file to your own repo, that way its harder to loose it): https://github.com/jesusvallejo/VolvoCanBusFirmware/blob/main/README.md

Cheers

**Comment by smartgauges** [comment]
Hello! Thank you very much for your work, I have added your file to my repository.

**Comment by jesusvallejo** [comment]
Hi, thanks, i have decompiled the code and it seems, the original code does not decode the VIN or nothing fancy, it just checks with multiple canbus addresses , for example, for the gear box it checks if(address==408 || address==428) bit shift ... etc. i hoped it was easier to extract more codes, sadly the info i have found ( extracting module info from diagnostic db) in other projects is not valid for us as they use the diagnostic address to "ask" for info instead of just listening. I still dont know how the tool can tell which module is responding after doing the call. thanks for your work.
