### ISSUE TITLE
Unable to flash canbus box 

### ISSUE THREAD

**Issue by liamstears** [smartgauges/canbox#5]
I've got 2 boxes that are slightly different, 1 flashes fine, this one however refuses, seems as though it's not even seen by the flasher

Just wondering if there is something obvious I am missing or maybe this is just a different design that cannot be flashed?

![20240506_194056](https://github.com/smartgauges/canbox/assets/67321276/4dfe353f-e239-48da-8ad8-b1567e484dfa)

**Comment by smartgauges** [comment]
hello, your board has different processor - hc32f072 instead of gd32f103, firmware for gd32f103 is not compatible with hc32f072.
https://github.com/SoCXin/HC32F072

**Comment by liamstears** [comment]
> hello, your board has different processor - hc32f072 instead of gd32f103, firmware for gd32f103 is not compatible with hc32f072. https://github.com/SoCXin/HC32F072

Thank you
